# Generated by Django 5.1.6 on 2025-03-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonFootprintRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_people', models.IntegerField()),
                ('monthly_kwh', models.IntegerField()),
                ('num_ac', models.IntegerField()),
                ('ac_hours', models.IntegerField()),
                ('num_fridge', models.IntegerField()),
                ('num_fans', models.IntegerField()),
                ('fan_hours', models.IntegerField()),
                ('num_tv', models.IntegerField()),
                ('tv_hours', models.IntegerField()),
                ('daily_car_km', models.IntegerField()),
                ('daily_bus_km', models.IntegerField()),
                ('daily_bike_km', models.IntegerField()),
                ('diet_type', models.CharField(max_length=10)),
                ('waste_type', models.CharField(max_length=10)),
                ('total_footprint', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
