# Generated by Django 5.1.6 on 2025-03-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carbon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonfootprintrecord',
            name='daily_train_km',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
