# Generated by Django 5.1.6 on 2025-03-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carbon', '0002_carbonfootprintrecord_daily_train_km'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbonfootprintrecord',
            name='waste_type',
        ),
    ]
