# Generated by Django 5.1.6 on 2025-03-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carbon', '0003_remove_carbonfootprintrecord_waste_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonfootprintrecord',
            name='daily_train_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
